[project]
name = "tardy"
version = "1.0.0"
description = "A simple Python package that tells you the time."
readme = "ReadMe.md"
requires-python = ">=3.13"
license = {text = "MIT"}
authors = [
  {name = "Rishyak", email = "hello@rishyak.com"},
]
keywords = ["time", "datetime", "clock"]
dependencies = [
  "pytz>=2025.2",
  "typer>=0.15.4",
  "yapf>=0.43.0",
]
